name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-18.04
    if: github.event.push.ref == 'refs/heads/master' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t kube-letsencrypt .

      - name: Tags
        run: |
          docker tag kube-letsencrypt ${{ secrets.DOCKER_USER }}/kube-letsencrypt:${{ github.sha }}
          docker tag kube-letsencrypt ${{ secrets.DOCKER_USER }}/kube-letsencrypt:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/kube-letsencrypt:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/ckube-letsencrypt:latest
